name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Ruff lint
        run: ruff check .
      - name: Black check
        run: black --check .
      - name: Mypy type-check
        run: mypy blrcs
      - name: Bandit security scan
        run: bandit -r blrcs -q
      - name: Run tests
        run: pytest -q
      - name: pip-audit
        run: pip-audit -r requirements.txt || true
