name: Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 1'

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links in docs
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose README.md docs/**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
